name: Build Android APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: android-actions/setup-android@v3
    - name: Install NDK and Gradle
      run: |
        sdkmanager --install "ndk;25.1.8937393" "cmake;3.22.1"
        sudo apt-get update && sudo apt-get install -y gradle
    - name: Build APK using System Gradle
      run: |
        gradle assembleDebug
    - name: Find and Upload any APK
      uses: actions/upload-artifact@v4
      with:
        name: PhoneRoomSLAM-APK
        path: "**/*.apk"
        
