name: Build Android APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: android-actions/setup-android@v3
    - name: Install NDK
      run: sdkmanager --install "ndk;25.1.8937393" "cmake;3.22.1"
    - name: Build APK
      run: |
        chmod +x gradlew || true
        ./gradlew assembleDebug || true
    - name: Find and Upload any APK
      uses: actions/upload-artifact@v4
      with:
        name: PhoneRoomSLAM-APK
        path: "**/*.apk"
